services:
  - type: web
    name: student-club-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: src/backend-express
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
