/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'social' : IDL.Null,
  'arts' : IDL.Null,
  'academic' : IDL.Null,
  'sports' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'clubId' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'authorName' : IDL.Text,
  'announcementId' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Application = IDL.Record({
  'status' : ApplicationStatus,
  'appliedAt' : Time,
  'clubName' : IDL.Text,
  'studentName' : IDL.Text,
  'applicationId' : IDL.Text,
  'email' : IDL.Text,
});
export const Club = IDL.Record({
  'clubId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'category' : Category,
});
export const Event = IDL.Record({
  'eventId' : IDL.Text,
  'title' : IDL.Text,
  'clubId' : IDL.Text,
  'attendeeCount' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'leader' : IDL.Null,
  'student' : IDL.Null,
});
export const Member = IDL.Record({
  'memberId' : IDL.Text,
  'clubId' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : Time,
  'role' : Role,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'approveApplication' : IDL.Func([IDL.Text], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createClub' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text],
      [],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
  'deleteClub' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
  'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getClub' : IDL.Func([IDL.Text], [Club], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'rejectApplication' : IDL.Func([IDL.Text], [], []),
  'updateClub' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
  'updateEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'arts' : IDL.Null,
    'academic' : IDL.Null,
    'sports' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'clubId' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'authorName' : IDL.Text,
    'announcementId' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Application = IDL.Record({
    'status' : ApplicationStatus,
    'appliedAt' : Time,
    'clubName' : IDL.Text,
    'studentName' : IDL.Text,
    'applicationId' : IDL.Text,
    'email' : IDL.Text,
  });
  const Club = IDL.Record({
    'clubId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'category' : Category,
  });
  const Event = IDL.Record({
    'eventId' : IDL.Text,
    'title' : IDL.Text,
    'clubId' : IDL.Text,
    'attendeeCount' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'leader' : IDL.Null,
    'student' : IDL.Null,
  });
  const Member = IDL.Record({
    'memberId' : IDL.Text,
    'clubId' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : Time,
    'role' : Role,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'approveApplication' : IDL.Func([IDL.Text], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createClub' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text],
        [],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
    'deleteClub' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
    'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getClub' : IDL.Func([IDL.Text], [Club], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'rejectApplication' : IDL.Func([IDL.Text], [], []),
    'updateClub' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Category], [], []),
    'updateEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };