/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'clubId' : string,
  'content' : string,
  'createdAt' : Time,
  'authorName' : string,
  'announcementId' : string,
}
export interface Application {
  'status' : ApplicationStatus,
  'appliedAt' : Time,
  'clubName' : string,
  'studentName' : string,
  'applicationId' : string,
  'email' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Category = { 'social' : null } |
  { 'arts' : null } |
  { 'academic' : null } |
  { 'sports' : null };
export interface Club {
  'clubId' : string,
  'name' : string,
  'createdAt' : Time,
  'memberCount' : bigint,
  'description' : string,
  'category' : Category,
}
export interface Event {
  'eventId' : string,
  'title' : string,
  'clubId' : string,
  'attendeeCount' : bigint,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface Member {
  'memberId' : string,
  'clubId' : string,
  'name' : string,
  'joinedAt' : Time,
  'role' : Role,
  'email' : string,
}
export type Role = { 'admin' : null } |
  { 'leader' : null } |
  { 'student' : null };
export type Time = bigint;
export interface _SERVICE {
  'approveApplication' : ActorMethod<[string], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'createClub' : ActorMethod<[string, string, string, Category], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, string, Time, string],
    undefined
  >,
  'deleteAnnouncement' : ActorMethod<[string], undefined>,
  'deleteClub' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'getAnnouncement' : ActorMethod<[string], Announcement>,
  'getApplications' : ActorMethod<[], Array<Application>>,
  'getClub' : ActorMethod<[string], Club>,
  'getEvent' : ActorMethod<[string], Event>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'rejectApplication' : ActorMethod<[string], undefined>,
  'updateClub' : ActorMethod<[string, string, string, Category], undefined>,
  'updateEvent' : ActorMethod<
    [string, string, string, string, Time, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];