/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Application {
    status: ApplicationStatus;
    appliedAt: Time;
    clubName: string;
    studentName: string;
    applicationId: string;
    email: string;
}
export type Time = bigint;
export interface Event {
    eventId: string;
    title: string;
    clubId: string;
    attendeeCount: bigint;
    date: Time;
    description: string;
    location: string;
}
export interface Member {
    memberId: string;
    clubId: string;
    name: string;
    joinedAt: Time;
    role: Role;
    email: string;
}
export interface Announcement {
    title: string;
    clubId: string;
    content: string;
    createdAt: Time;
    authorName: string;
    announcementId: string;
}
export interface Club {
    clubId: string;
    name: string;
    createdAt: Time;
    memberCount: bigint;
    description: string;
    category: Category;
}
export enum ApplicationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Category {
    social = "social",
    arts = "arts",
    academic = "academic",
    sports = "sports"
}
export enum Role {
    admin = "admin",
    leader = "leader",
    student = "student"
}
export interface backendInterface {
    approveApplication(applicationId: string): Promise<void>;
    createAnnouncement(announcementId: string, title: string, content: string, clubId: string, authorName: string): Promise<void>;
    createClub(clubId: string, name: string, description: string, category: Category): Promise<void>;
    createEvent(eventId: string, title: string, description: string, clubId: string, date: Time, location: string): Promise<void>;
    deleteAnnouncement(announcementId: string): Promise<void>;
    deleteClub(clubId: string): Promise<void>;
    deleteEvent(eventId: string): Promise<void>;
    getAnnouncement(announcementId: string): Promise<Announcement>;
    getApplications(): Promise<Array<Application>>;
    getClub(clubId: string): Promise<Club>;
    getEvent(eventId: string): Promise<Event>;
    getMembers(): Promise<Array<Member>>;
    rejectApplication(applicationId: string): Promise<void>;
    updateClub(clubId: string, name: string, description: string, category: Category): Promise<void>;
    updateEvent(eventId: string, title: string, description: string, clubId: string, date: Time, location: string, attendeeCount: bigint): Promise<void>;
}
import type { Application as _Application, ApplicationStatus as _ApplicationStatus, Category as _Category, Club as _Club, Member as _Member, Role as _Role, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0);
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createClub(arg0: string, arg1: string, arg2: string, arg3: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClub(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClub(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteClub(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClub(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClub(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async getAnnouncement(arg0: string): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncement(arg0);
            return result;
        }
    }
    async getApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClub(arg0: string): Promise<Club> {
        if (this.processError) {
            try {
                const result = await this.actor.getClub(arg0);
                return from_candid_Club_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClub(arg0);
            return from_candid_Club_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return result;
        }
    }
    async getMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplication(arg0);
            return result;
        }
    }
    async updateClub(arg0: string, arg1: string, arg2: string, arg3: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClub(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClub(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Club_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Club): Club {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Member_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Member {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: string;
    clubId: string;
    name: string;
    joinedAt: _Time;
    role: _Role;
    email: string;
}): {
    memberId: string;
    clubId: string;
    name: string;
    joinedAt: Time;
    role: Role;
    email: string;
} {
    return {
        memberId: value.memberId,
        clubId: value.clubId,
        name: value.name,
        joinedAt: value.joinedAt,
        role: from_candid_Role_n15(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApplicationStatus;
    appliedAt: _Time;
    clubName: string;
    studentName: string;
    applicationId: string;
    email: string;
}): {
    status: ApplicationStatus;
    appliedAt: Time;
    clubName: string;
    studentName: string;
    applicationId: string;
    email: string;
} {
    return {
        status: from_candid_ApplicationStatus_n6(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        clubName: value.clubName,
        studentName: value.studentName,
        applicationId: value.applicationId,
        email: value.email
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clubId: string;
    name: string;
    createdAt: _Time;
    memberCount: bigint;
    description: string;
    category: _Category;
}): {
    clubId: string;
    name: string;
    createdAt: Time;
    memberCount: bigint;
    description: string;
    category: Category;
} {
    return {
        clubId: value.clubId,
        name: value.name,
        createdAt: value.createdAt,
        memberCount: value.memberCount,
        description: value.description,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    arts: null;
} | {
    academic: null;
} | {
    sports: null;
}): Category {
    return "social" in value ? Category.social : "arts" in value ? Category.arts : "academic" in value ? Category.academic : "sports" in value ? Category.sports : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    leader: null;
} | {
    student: null;
}): Role {
    return "admin" in value ? Role.admin : "leader" in value ? Role.leader : "student" in value ? Role.student : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Array<Member> {
    return value.map((x)=>from_candid_Member_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    social: null;
} | {
    arts: null;
} | {
    academic: null;
} | {
    sports: null;
} {
    return value == Category.social ? {
        social: null
    } : value == Category.arts ? {
        arts: null
    } : value == Category.academic ? {
        academic: null
    } : value == Category.sports ? {
        sports: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
